version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/alerts-src'
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    ignore:
      - dependency-name: "node"
        versions: ["17.x","18.x"]
    commit-message:
      prefix: BAU
  - package-ecosystem: 'npm'
    directory: '/heartbeat-src'
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    ignore:
      - dependency-name: "node"
        versions: ["17.x","18.x"]
    commit-message:
      prefix: BAU
  - package-ecosystem: 'npm'
    directory: '/slack-src'
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
      - dependabot
    ignore:
      - dependency-name: "node"
        versions: ["17.x","18.x"]
    commit-message:
      prefix: BAU
