name: build-and-release-slack-lambda
on:
  push:
    branches:
      - main
    paths:
      - slack-src/**

jobs:
  build-and-release-slack-lambda:
    uses: ./.github/workflows/build-and-release.yml
    with:
      src-dir: slack-src
      zipname: slack.zip
      version: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
    secrets:
      AWS_DEPLOYER_ROLE: ${{ secrets.AWS_DEPLOYER_ROLE }}
      SIGNING_PROFILE: ${{ secrets.SIGNING_PROFILE }}
      VERSIONED_ARTEFACT_BUCKET: ${{ secrets.VERSIONED_ARTEFACT_BUCKET }}
      SIGNED_ARTEFACT_DESTINATION_BUCKET: ${{ secrets.SIGNED_ARTEFACT_DESTINATION_BUCKET }}
    permissions:
      id-token: write
      contents: read